### ISSUE TITLE
搭建出错

### ISSUE THREAD

**Issue by alonedogboy** [unioreox/PagerMaid-Pyro-PaaS#1]
好像不行哎
![image](https://user-images.githubusercontent.com/61310130/213345391-15419c7c-cfff-4a44-a758-93f750111ffb.png)

![image](https://user-images.githubusercontent.com/61310130/213345347-90a33fec-3a16-4d99-943e-484360a98cbe.png)

**Comment by unioreox** [comment]
Netlify好像不能部署docker吧

**Comment by alonedogboy** [comment]
> Netlify 好象不能安装docker吧
换成了koyeb也不行
![image](https://user-images.githubusercontent.com/61310130/213350331-e7fbba68-9e0b-4581-8572-17e0a4243b65.png)

**Comment by unioreox** [comment]
> > Netlify 好象不能安装docker吧
> 换成了koyeb也不行
> ![image](https://user-images.githubusercontent.com/61310130/213350331-e7fbba68-9e0b-4581-8572-17e0a4243b65.png)
> 

没有push镜像

**Comment by alonedogboy** [comment]
> > > Netlify 好象不能安装docker吧
> > > 换成了koyeb也不行
> > > ![image](https://user-images.githubusercontent.com/61310130/213350331-e7fbba68-9e0b-4581-8572-17e0a4243b65.png)
> 
> 没有push镜像

不是可以直接通过GitHub部署吗
![image](https://user-images.githubusercontent.com/61310130/213350876-b2b3c611-05bf-4b00-9880-531e91c49539.png)
